### PR TITLE
Build dynamic framework to support carthage

### PR DESCRIPTION
**Pull request by jietab**

### CODE REVIEW

**Comment by ConEliopoulos** [comment]
@jietab The framework target and demo project were not compiling, so I added a fixup commit. Please let me know if it looks ok to you.

**Comment by ConEliopoulos** [comment]
@jietab I added a couple more commits on top. I removed the `lib` target and made some changes to the directory that is more aligned with our standard project setup.

Also, looks like the framework is static, not dynamic 🙂 So we can update the commit message as well.

**Comment by jietab** [comment]
@ConEliopoulos  Thanks for the changes, it looks great!

**Review by ConEliopoulos — APPROVED** [review]
LGTM

**Pull request merged**
